alpha1=ARTY:New(GROUP:FindByName("Alpha 1"))
alpha1:AddToCluster("Alpha")
alpha1:AddToCluster("Short")
alpha1:SetRearmingGroup(GROUP:FindByName("Alpha Reloader"))
alpha1:SetMarkAssignmentsOn()
alpha1:SetTacNukeShells(5)
alpha1:SetTacNukeWarhead(0.5)
alpha1:Start()

alpha2=ARTY:New(GROUP:FindByName("Alpha 2"))
alpha2:AddToCluster("Alpha")
alpha2:AddToCluster("Short")
alpha2:SetRearmingGroup(GROUP:FindByName("Alpha Reloader"))
alpha2:SetMarkAssignmentsOn()
alpha2:Start()

bravo1=ARTY:New(GROUP:FindByName("Bravo 1"))
bravo1:AddToCluster("Bravo")
bravo1:AddToCluster("Short")
bravo1:SetRearmingGroup(GROUP:FindByName("Bravo Reloader"))
bravo1:SetMarkAssignmentsOn()
bravo1:SetTacNukeShells(5)
bravo1:SetTacNukeWarhead(0.5)
bravo1:Start()

bravo2=ARTY:New(GROUP:FindByName("Bravo 2"))
bravo2:AddToCluster("Bravo")
bravo2:AddToCluster("Short")
bravo2:SetRearmingGroup(GROUP:FindByName("Bravo Reloader"))
bravo2:SetMarkAssignmentsOn()
bravo2:Start()

long1=ARTY:New(GROUP:FindByName("Long 1"))
long1:AddToCluster("Long")
long1:SetRearmingGroup(GROUP:FindByName("Long Reloader"))
long1:SetMarkAssignmentsOn()
long1:Start()

long2=ARTY:New(GROUP:FindByName("Long 2"))
long2:AddToCluster("Long")
long2:SetRearmingGroup(GROUP:FindByName("Long Reloader"))
long2:SetMarkAssignmentsOn()
long2:Start()

perry1=ARTY:New(GROUP:FindByName("Perry 1"))
perry1:AddToCluster("Perry")
perry1:SetMarkAssignmentsOn()
perry1:SetTacNukeShells(5)
perry1:SetTacNukeWarhead(0.5)
perry1:Start()

perry2=ARTY:New(GROUP:FindByName("Perry 2"))
perry2:AddToCluster("Perry")
perry2:SetMarkAssignmentsOn()
perry2:SetTacNukeShells(5)
perry2:SetTacNukeWarhead(0.5)
perry2:Start()
